version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "ngx_metafrenzy"
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
      - /app/node_modules
